### ISSUE TITLE
Create an Analyzer to Ensure only One Public Method per Endpoint

### ISSUE THREAD

**Issue by ardalis** [ardalis/ApiEndpoints#13]
Endpoints are actually just controllers, and if they had more public methods beyond the one defined in the class, they could still act as Actions and be routed to by the framework. Create an Analyzer to warn if someone is adding additional public methods to a class that inherits from an Endpoint base class.

**Comment by JoeyMckenzie** [comment]
Started working on this issue on [my fork](https://github.com/JoeyMckenzie/ApiEndpoints/tree/master/src/Ardalis.ApiEndpoints.Analyzers), currently a WIP, but basic functionality is there (light bulb notification, refactor to remove method). Should have some time later this week write more tests, but will happily accept any help.

**Comment by ppittle** [comment]
Damn, @JoeyMckenzie beat me to it - also started working on adding an analyzer; Work In Progress [PR](https://github.com/ardalis/ApiEndpoints/pull/25). 

![image](https://user-images.githubusercontent.com/1190907/87644284-c9ee8180-c700-11ea-869f-4a1c33d9a7ed.png)

**Comment by ardalis** [comment]
maybe you two can work together and merge the best of your two approaches...

**Comment by tiesmaster** [comment]
Funny, I came here to check the status of this. I heard the shout out from @ardalis on the .NET Rocks podcast. I guess I wasn't the only one that heard it 😅  Really good to hear this is getting picked up :)

**Comment by ppittle** [comment]
@JoeyMckenzie - I reviewed what you had and our approaches are pretty similar.  I have yet to implement a CodeFixProvider if you want to help out.  My thinking is to make any erronous public methods internal.  Though it would be interesting to additionally offer to convert a public method to a new ApiEndpoint, though that would be substantially more complex.

**Comment by ppittle** [comment]
So the Analyzer is working, as can be seen from the screen shot above.  But I'm having a hard time getting the Code Fix Provider to register and show up in Visual Studio.

If anyone can help, I've put a question out on StackOverflow:  https://stackoverflow.com/questions/62985602/add-codefixprovider-to-existing-nuget-pacakge

Otherwise, it might be best to launch first with just the Analyzer that provides the warning, and then have a later release that includes a Code Fix Provider that will help developers change their method from public to internal.

**Comment by ardalis** [comment]
Give Paulo's answer a try and put it in its own package?

**Comment by JoeyMckenzie** [comment]
Been slacking on this issue for a while, I'll get back to it this week. @ppittle is there any particular reason you added the analyzer to the package, rather than creating a separate VSIX project? My concerns are similar to Paulo's, as we would want to give consumers the option of using the analyzer as not everyone might have some sort of Roslynator extension, or even analyzers to that point, enabled or installed.

I think, too, creating it as a separate analyzer/VSIX project, it's a lot easier to debug since you can just run another VS instance with the analyzer enabled on a sample project.

**Comment by ppittle** [comment]
@ardalis / @JoeyMckenzie - I'll explore putting the analyzer into a different nuget package as suggested on [Stack Overflow](https://stackoverflow.com/questions/62985602/add-codefixprovider-to-existing-nuget-pacakge).

I did consider this approach initially but chose to try and go with the single nuget package for these reasons:
- I don't think it makes sense to use the VSIX - I don't think it's reasonable to expect a user of this package to additionally install a Visual Studio Extensions.  Especially if it's a manual process on top of adding the nuget package to a project, which I'm pretty sure it is.
- The dependency graph is I think going to need to grow a bit.  Basically we'll need `ApiEndpoints.csproj` and `ApiEndpoints.Analyzers.csproj`.  However, Analyzers currently depend on `ApiEndpoints.BaseAsycnEndpoint`.   But if Analyzers is going to be in a new nuget package, the current package will need to have a package dependency on Analyzers in order to have the Analyzers auto install whenever someone installs the ApiEndpoints nuget package.  If there was a project dependency, ie `ApiEndpoints.csproj` depended on `ApiEndpoints.Analyzers.csproj` I believe `dotnet pack` would wire up the nuget dependencies automatically.  However, because of this circular dependency between Analyzers and ApiEndpoints I could add a new project that both depended on that contained some marker interface the Analyzers could use.  Or figure out a way to fix the dotnet pack issue with MSBuild.

**Comment by ardalis** [comment]
Done and published.
https://www.nuget.org/packages/Ardalis.ApiEndpoints.CodeAnalyzers
