### ISSUE TITLE
Great! But ... 

### ISSUE THREAD

**Issue by MichielCornilleESC** [ardalis/ApiEndpoints#48]
Hello, this is not really an issue, as much as a set of thoughts...
 
Thank you for sharing this remarkable piece of open source software!  I do feel however that it would be better suited as a PR to Asp.NET core, maybe as an official Microsoft package. It feels like something that inherently fits in Microsoft's mindset around Razor pages.

Secondly I noticed you discuss MediatR. I do think those concepts are related and not related at the same time.
MediatR (IMHO) sits between UI and Application/Domain/...  whatever you call it.  This package sits between IIS/Kestrel and UI so to speak.

It is perfectly possible (and I would even prefer it) to use this library and still use MediatR to dispatch Commands/Queries.
 
 Thoughts?

**Comment by ardalis** [comment]
I don't disagree that this could easily be part of Microsoft's ASP.NET Core, and I initially provided this feedback directly to the team. Most recently I've discussed the ideas with @bradygaster who is looking at different ways folks can build APIs in ASP.NET Core.

And certainly you can use MediatR alongside this package/pattern. I only mention it because many developers I know have used MediatR or something similar to solve the problem caused by controllers becoming overly large. Thanks!

**Comment by bradygaster** [comment]
We did discuss this as @ardalis points out. I think it is safe to say that we're hearing from folks that projects like Steve's and the Carter Project are sending a loud-and-clear message that the ASP.NET team could make investments in a non-MVC*ish* way to do APIs. And we're certainly listening. Stay tuned. :)

**Comment by ErikEJ** [comment]
See https://github.com/dotnet/aspnetcore/issues/27724
